// <auto-generated />
using System;
using HogarGestor.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HogarGestor.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220831051824_Segunda")]
    partial class Segunda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("historia");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_PatronCrecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Cls_BeneficiarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("tipoPatronC")
                        .HasColumnType("int");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Cls_BeneficiarioId");

                    b.ToTable("patronCrecimiento");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Cls_Persona");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_SugerenciasCuidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Cls_HistoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cls_HistoriaId");

                    b.ToTable("sugerencia");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_Beneficiario", b =>
                {
                    b.HasBaseType("HogarGestor.App.Dominio.Cls_Persona");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("familiarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("historiaClinicaId")
                        .HasColumnType("int");

                    b.Property<float>("latitud")
                        .HasColumnType("real");

                    b.Property<float>("longitud")
                        .HasColumnType("real");

                    b.Property<int>("nutricionistaId")
                        .HasColumnType("int");

                    b.Property<int>("pediatraId")
                        .HasColumnType("int");

                    b.HasIndex("familiarId");

                    b.HasIndex("historiaClinicaId");

                    b.HasIndex("nutricionistaId");

                    b.HasIndex("pediatraId");

                    b.HasDiscriminator().HasValue("Cls_Beneficiario");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_Familiar", b =>
                {
                    b.HasBaseType("HogarGestor.App.Dominio.Cls_Persona");

                    b.Property<string>("parentesco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Cls_Familiar");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_PersonalSalud", b =>
                {
                    b.HasBaseType("HogarGestor.App.Dominio.Cls_Persona");

                    b.Property<int>("especialidad")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Cls_PersonalSalud");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_PatronCrecimiento", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Cls_Beneficiario", null)
                        .WithMany("patronCrecimiento")
                        .HasForeignKey("Cls_BeneficiarioId");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_SugerenciasCuidado", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Cls_Historia", null)
                        .WithMany("sugerencias")
                        .HasForeignKey("Cls_HistoriaId");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_Beneficiario", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Cls_Familiar", "familiar")
                        .WithMany()
                        .HasForeignKey("familiarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HogarGestor.App.Dominio.Cls_Historia", "historiaClinica")
                        .WithMany()
                        .HasForeignKey("historiaClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HogarGestor.App.Dominio.Cls_PersonalSalud", "nutricionista")
                        .WithMany()
                        .HasForeignKey("nutricionistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HogarGestor.App.Dominio.Cls_PersonalSalud", "pediatra")
                        .WithMany()
                        .HasForeignKey("pediatraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("familiar");

                    b.Navigation("historiaClinica");

                    b.Navigation("nutricionista");

                    b.Navigation("pediatra");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_Historia", b =>
                {
                    b.Navigation("sugerencias");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Cls_Beneficiario", b =>
                {
                    b.Navigation("patronCrecimiento");
                });
#pragma warning restore 612, 618
        }
    }
}
